version: "3.3"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./database:/data/db

  web:
    image: meteorjs/todos:latest
    container_name: web
    restart: always
    ports:
      - "3666:3000"
    links:
      - mongo:mongodb.docker.local
    environment:
      - ROOT_URL=http://localhost
      - MONGO_URL=mongodb://mongodb.docker.local:27017/production
    volumes:
      - ./database:/data/db

  proxy:
    image: nginx:alpine
    container_name: proxy
    restart: always
    ports:
      - "80:80"
    links:
      - web:web.docker.local
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
