version: "3"

services:
  web:
    build: .
    # command: nodemon --nolazy --inspect-brk=0.0.0.0:9229 src/app.js
    command: nodemon --nolazy --inspect=0.0.0.0:9229 src/app.js
    volumes:
      - .:/code
    ports:
      - "3666:3666"
      - "9229:9229"
